[package]
name = "Hconfig"
version = "1.0.0"
authors = ["Hyultis <hyultis@use.startmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
json = "0.12.4"
HArcMut = { path = "../HArcMut" }
dashmap = "5.4.0"
arc-swap = "1.6.0"
thiserror = "1.0.40"
