name: tests-and-publish
run-name: Check code and publish new version on crate.IO
on: [ workflow_dispatch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    runs-on: ubuntu-latest
    needs: security_audit
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo tests
        run: cargo test --test tests

  publish:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          #dry-run: true
