name: check-and-publish
run-name: Check code and publish new version on crate.io
on: [workflow_dispatch]
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions-rs/toolchain@v1
                with:
                    toolchain: stable
                    override: true
            -   name: Run cargo check
                uses: actions-rs/cargo@v1
                with:
                    command: test --test tests

    publish:
        runs-on: ubuntu-latest
        needs: tests
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions-rs/toolchain@v1
                with:
                    toolchain: stable
                    override: true
            -   uses: katyo/publish-crates@v2
                with:
                    registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
                    dry-run: true
